const Payment = require('./payment.model');
const Order = require('../order/order.model');

exports.findAll = (query = {}) => {
    const filter = {};
    if (query.customerId) filter.customerId = query.customerId;
    if (query.orderId) filter.orderId = query.orderId;
    if (query.status) filter.status = query.status;
    if (query.method) filter.method = query.method;
    const page = parseInt(query.page) || 1;
    const limit = parseInt(query.limit) || 20;
    return Payment.find(filter)
        .populate('orderId', 'status deliveryType total')
        .populate('customerId', 'name email phone')
        .sort('-createdAt').skip((page - 1) * limit).limit(limit);
};

exports.findById = (id) => Payment.findById(id).populate('orderId').populate('customerId', 'name email phone');

/**
 * Initiate a payment — called after order is created.
 */
exports.initiate = async (data) => {
    const payment = await Payment.create(data);

    // For COD, auto-mark as pending until delivery
    if (data.method === 'cashOnDelivery') {
        return payment;
    }

    // For digital payments, return the payment record
    // (the actual gateway redirect URL would be generated by khalti/esewa/fonepay service)
    return payment;
};

/**
 * Verify payment callback from gateway (Khalti/eSewa/FonePay).
 */
exports.verify = async (paymentId, gatewayResponse) => {
    const payment = await Payment.findById(paymentId);
    if (!payment) throw Object.assign(new Error('Payment not found'), { statusCode: 404 });

    payment.gatewayResponse = gatewayResponse;
    payment.status = gatewayResponse.success ? 'success' : 'failed';

    if (payment.status === 'success') {
        await Order.findByIdAndUpdate(payment.orderId, { paymentStatus: 'paid' });
    }

    return payment.save();
};

/**
 * Process refund.
 */
exports.refund = async (paymentId) => {
    const payment = await Payment.findById(paymentId);
    if (!payment) throw Object.assign(new Error('Payment not found'), { statusCode: 404 });
    if (payment.status !== 'success') throw Object.assign(new Error('Can only refund successful payments'), { statusCode: 400 });
    payment.status = 'refunded';
    await Order.findByIdAndUpdate(payment.orderId, { paymentStatus: 'refunded' });
    return payment.save();
};
